openapi: 3.0.0
info:
  title: TodoList
  description: API
  version: 0.1.9

servers:
  # - url: https://movie-quotes-back-production.up.railway.app/api
  # description: production server
  - url: http://localhost:3000/api
    description: local server
# components:
#   securitySchemes:
#     bearerAuth:
#       type: http
#       scheme: bearer
#       bearerFormat: JWT
paths:
  /newItem:
    post:
      tags:
        - Todo
      requestBody:
        description: add the new todo item
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                task:
                  type: string
                completed:
                  type: boolean
      responses:
        "201":
          description: new item is added
  /items:
    get:
      tags:
        - Todo
      responses:
        "200":
          description: get all items data
  /items/{id}:
    put:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      tags:
        - Todo
      responses:
        "200":
          description: update item content
    delete:
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
      tags:
        - Todo
      responses:
        "200":
          description: item deleted successfully
  /items/completed:
    delete:
      tags:
        - Todo
      responses:
        "200":
          description: completed items deleted successfully
